dataset: depth_dataset
seed: 1

wm:
  latent_dim: 4096
  num_actions: 4
  alpha: 0.80
  beta_rec: 1.0
  beta_kl: 1.0
  discrete_latent_state: True

model:
  d_model: 1024
  n_layers: 2
  n_blocks: 3
  dropout: 0.01
  layer:
    l_max: 99
    N: 128

train:
  epochs: 25
  bsz: 4
  lr: 0.0001
  lr_schedule: true
  weight_decay: 0.01
  checkpoint: true

wandb:
  mode: online
  project: S4WM