dataset: depth_dataset
seed: 72

wm:
  rnn_mode: False
  sample_mean: False
  image_dist_type: "MSE"
  latent_dist_type: "Gaussian"
  latent_dim: 256
  alpha: 0.8
  beta_rec: 1.0
  beta_kl: 0.2
  clip_kl_loss: True
  kl_lower_bound: 1.0
  loss_reduction: "sum"


model:
  d_model: 1024   
  n_layers: 2
  n_blocks: 12
  dropout: 0.5
  layer:
    l_max: 99
    N: 100

train:
  epochs: 100
  bsz: 8
  lr: 0.0002
  lr_schedule: true
  weight_decay: 0.01
  checkpoint: true

wandb:
  mode: online
  project: S4WM