dataset: depth_dataset
seed: 6

wm:
  latent_dim: 1024
  num_actions: 4
  alpha: 0.7
  beta_rec: 1.0
  beta_kl: 1.0
  discrete_latent_state: True

model:
  d_model: 512
  n_layers: 2
  n_blocks: 6
  dropout: 0.05
  layer:
    l_max: 99
    N: 64

train:
  epochs: 50
  bsz: 4
  lr: 0.0001
  lr_schedule: true
  weight_decay: 0.01
  checkpoint: true

wandb:
  mode: online
  project: S4WM