dataset: quad_depth_trajectories
layer: s4
seed: 0

wm:
  latent_dim: 256
  num_actions: 4
  alpha: 0.8
  beta_rec: 0.8
  beta_kl: 0.2
  discrete_latent_state: False

model:
  d_model: 260
  d_output: 256
  n_layers: 5
  layer:
    l_max: 19
    N: 128

train:
  epochs: 100
  bsz: 256
  lr: 0.001
  lr_schedule: True
  weight_decay: 0.05
  checkpoint: true
  suffix: null # String to use for checkpoint suffix
  sample: null # Sample during validation with desired prefix length

# Pass in 'wandb.mode=online' to turn on wandb logging
wandb:
  mode: disabled
  project: s4
  entity: null
