dataset: quad_depth_trajectories
layer: s4
seed: 0

wm:
  latent_dim: 256
  num_actions: 4
  alpha: 0.8
  beta_rec: 1.0
  beta_kl: 1.0
  discrete_latent_state: False

model:
  d_model: 512
  d_output: 256
  n_layers: 2
  dropout: 0.0
  layer:
    l_max: 19
    N: 128

train:
  epochs: 10
  bsz: 100
  lr: 0.0001
  lr_schedule: false
  weight_decay: 0.05
  checkpoint: true
  suffix: null # String to use for checkpoint suffix
  sample: null # Sample during validation with desired prefix length

# Pass in 'wandb.mode=online' to turn on wandb logging
wandb:
  mode: disabled
  project: s4
  entity: null
