dataset: depth_dataset
layer: s4
seed: 5

wm:
  latent_dim: 256
  num_actions: 4
  alpha: 0.8
  beta_rec: 1.0
  beta_kl: 1.0
  discrete_latent_state: False

model:
  d_model: 512
  n_layers: 4
  n_blocks: 3
  dropout: 0.05
  layer:
    l_max: 74
    N: 64

train:
  epochs: 200
  bsz: 2
  lr: 0.00001
  lr_schedule: true
  weight_decay: 0.05
  checkpoint: true

wandb:
  mode: online
  project: S4WM