dataset: depth_dataset
seed: 1

wm:
  latent_dim: 1024
  num_actions: 4
  alpha: 0.80
  beta_rec: 1.0
  beta_kl: 0.1
  discrete_latent_state: True

model:
  d_model: 2048
  n_layers: 2
  n_blocks: 2
  dropout: 0.5
  layer:
    l_max: 99
    N: 64

train:
  epochs: 40
  bsz: 8
  lr: 0.00015
  lr_schedule: True
  weight_decay: 0.001
  checkpoint: true

wandb:
  mode: online
  project: S4WM