dataset: depth_dataset
seed: 1

wm:
  latent_dim: 1024
  num_actions: 4
  alpha: 0.80
  beta_rec: 1.0
  beta_kl: 0.2
  discrete_latent_state: True

model:
  d_model: 1024
  n_layers: 2
  n_blocks: 8
  dropout: 0.05
  layer:
    l_max: 99
    N: 64

train:
  epochs: 30
  bsz: 4
  lr: 0.0005
  lr_schedule: True
  weight_decay: 0.05
  checkpoint: true

wandb:
  mode: online
  project: S4WM