dataset: depth_dataset
layer: s4
seed: 5

wm:
  latent_dim: 512
  num_actions: 4
  alpha: 0.8
  beta_rec: 1.0
  beta_kl: 1.0
  discrete_latent_state: False

model:
  d_model: 512
  n_layers: 2
  dropout: 0.1
  layer:
    l_max: 74
    N: 128

train:
  epochs: 200
  bsz: 2
  lr: 0.0001
  lr_schedule: true
  weight_decay: 0.05
  checkpoint: true

wandb:
  mode: online
  project: S4WM